<a href="https://colab.research.google.com/github/Yongjin9660/tensorflow_Ex/blob/master/Hidden_Layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

히든레이어
  - 보스톤 집값 예측 : https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv
  - 아이리스 품종 분류 : https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv

In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

**보스턴 집값 예측**

In [2]:
# 1. 과거의 데이터를 준비합니다.
보스턴 = pd.read_csv('https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv')
print(보스턴.columns)

# 독립변수, 종속변수 분리
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
(506, 13) (506, 1)


In [10]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [11]:
model.summary()

Model: "functional_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_5 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [9]:
# 3. 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 19.2117
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 18.7793
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 19.7107
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 17.8928
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 20.3092
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 18.5018
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 20.2245
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 19.1552
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 19.3283
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 18.7233


In [12]:
# 4. 모델을 이용합니다.
model.predict(독립[0:5])
print(종속[:5])

   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


**아이리스 품종** **분류**

In [13]:
# 1. 과거의 데이터를 준비합니다.
아이리스 = pd.read_csv('https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv')
# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)

# 독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [18]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [19]:
# 3. 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0472 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0460 - accuracy: 0.9867
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0489 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0544 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0529 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0499 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0438 - accuracy: 0.9867
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0435 - accuracy: 0.9867
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0440 - accuracy: 0.9867
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0445 - accuracy: 0.9800


In [20]:
# 모델을 이용합니다.
print(model.predict(독립[0:5]))
print(종속[0:5])

[[1.0000000e+00 1.5609917e-09 4.0281624e-12]
 [1.0000000e+00 4.3191072e-08 2.8924045e-11]
 [1.0000000e+00 1.0501678e-08 2.6079760e-11]
 [9.9999988e-01 6.2240588e-08 3.5264514e-11]
 [1.0000000e+00 1.0225466e-09 3.6393284e-12]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
